// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for KeyGeneratorFunction
 */
export interface KeyGeneratorFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/key-generator/key-generator.
 */
export class KeyGeneratorFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: KeyGeneratorFunctionProps) {
    super(scope, id, {
      description: 'src/key-generator/key-generator.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/key-generator/key-generator.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}